### ISSUE TITLE
[BUG] --expression parameter for kallisto tsv not able to be found

### ISSUE THREAD

**Issue by MujeebQadiri** [ConesaLab/SQANTI3#445]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [x] I have loaded the SQANTI3.env conda environment

### Problem description

First of all, thank you for this incredible tool I am excited to run it on some ONT data we have however I am running into an error when using the expression matrix of matching single-end short read data quantified with Kallisto. If I run the analysis without the -e parameter I am able to get the program going, however it seems that I am not able to get it to point towards the expression matrix.

It would appear the file is not splitting during the execution of this chunk:

```
    # Expression checks
    if args.expression is not None:
        if os.path.isdir(args.expression)==True:
            print("Expression files located in {0} folder".format(args.expression), file=sys.stderr)
        else:
            for f in args.expression.split(','):
                if not os.path.exists(f):
                        print("Expression file {0} not found. Abort!".format(f), file=sys.stderr)
                        sys.exit(1)
```

### Code sample
```
REFERENCE_GTF=/n/groups/flyrnai/mujeeb/References/genome/Drosophila_melanogaster.BDGP6.46.112.gtf
REFERENCE_GENOME=/n/groups/flyrnai/mujeeb/References/genome/Drosophila_melanogaster.BDGP6.46.dna.toplevel.fa
NOVEL_GTF=/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/bambu/extended_annotations.gtf
FULL_LENGTH=/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/bambu/FL_counts.csv
SHORT_READ_BAM=/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/Alignments/
SHORT_READ_SJ_OUT=/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/SJ_Files/SRR7072111SJ.out.tab,/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/SJ_Files/SRR7072112SJ.out.tab,/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/SJ_Files/SRR7072113SJ.out.tab,/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/SJ_Files/SRR7072114SJ.out.tab
SHORT_READ_KALLISTO=/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/SJ_Files/1abundance.tsv,/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/SJ_Files/2abundance.tsv,/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/SJ_Files/3abundance.tsv,/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/SJ_Files/4abundance.tsv

python3 /home/muq664/linuxpackages/sqanti3/sqanti3_qc.py ${NOVEL_GTF} ${REFERENCE_GTF} ${REFERENCE_GENOME} \
    -o D8 \
    -d SQANTI3_output_2 \
    -fl ${FULL_LENGTH} \
    --SR_bam ${SHORT_READ_BAM} \
    -c ${SHORT_READ_SJ_OUT} \
    -e ${SHORT_READ_KALLISTO} \
    --cpus 1 \
    --report both \
    --skipORF \
    --force_id_ignore
```
### Error

WARNING: output directory SQANTI3_output_2 already exists. Overwriting!
ERROR: File /n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/SJ_Files/1abundance.tsv,/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/SJ_Files/2abundance.tsv,/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/SJ_Files/3abundance.tsv,/n/groups/flyrnai/mujeeb/bulkRNA/Younshim/12092024_Yki_Wt_NanoPore_D1D2D5D8/SQANTI3_output/STAR_mapping/SJ_Files/4abundance.tsv not found. Abort!

**Comment by MujeebQadiri** [comment]
I want to add I also installed SQANTI3 separately on my local computer to see if there was an environment issue using DOCKER and receive the same error.

Thank you in advance!

**Comment by jordana-olive** [comment]
Hello, there!

I am having the same issue. I tried both conda and Docker envs, tried to change to comma-separated files and path with the files. Nothing solved it. 

Any updates? 
Thanks!

**Comment by pabloati** [comment]
This has been fixed, it was an small error with the checks that SQANTI3 did with the inputs. It will be updated in the next release asap (5.4)

**Comment by MujeebQadiri** [comment]
> This has been fixed, it was an small error with the checks that SQANTI3 did with the inputs. It will be updated in the next release asap (5.4)

Thank you so much Pablo, looking forward to re-running this analysis using the short-read expression :)!

**Comment by pabloati** [comment]
It is now live, try to download it and let me know if it works fine :)

**Comment by MujeebQadiri** [comment]
Hi @pabloati 

I updated SQANTI3 to the latest release v5.4 and unfortunately I still have the same error. Not sure how to re-open the issue or if I should submit a new issue.

Thank you so much for your help!

Best,
Mujeeb

```
(sqanti3) drsc-linux@drsclinux-Precision-3660:~/Documents/Projects/With/Younshim/04_28_2025_ONT$ python3 /home/drsc-linux/Documents/Tools/sqanti3/release_sqanti3/sqanti3_qc.py -v

    =====================
      ░██████╗░░█████╗░
      ██╔═══██╗██╔══██╗
      ██║██╗██║██║░░╚═╝
      ╚██████╔╝██║░░██╗
      ░╚═██╔═╝░╚█████╔╝
      ░░░╚═╝░░░░╚════╝░
    =====================
    
SQANTI3 5.4
(sqanti3) X~/Documents/Projects/With/X/04_28_2025_ONT$ ls
D8_SQANTI_BAMBU  input_data  short_reads
(sqanti3) X:~/Documents/Projects/With/X/04_28_2025_ONT$ tree
.
├── D8_SQANTI_BAMBU
│   └── logs
│       └── sqanti3.log
├── input_data
│   ├── abundances
│   │   ├── SRR707211_abundance.tsv
│   │   ├── SRR707212_abundance.tsv
│   │   ├── SRR707213_abundance.tsv
│   │   └── SRR707214_abundance.tsv
│   ├── Alignments
│   │   ├── SRR7072111Aligned.sortedByCoord.out.bam
│   │   ├── SRR7072112Aligned.sortedByCoord.out.bam
│   │   ├── SRR7072113Aligned.sortedByCoord.out.bam
│   │   └── SRR7072114Aligned.sortedByCoord.out.bam
│   ├── D8_SQANTI_REF_classification.txt
│   ├── Drosophila_melanogaster.BDGP6.46.112.gtf
│   ├── Drosophila_melanogaster.BDGP6.46.dna.toplevel.fa
│   ├── Drosophila_melanogaster.BDGP6.46.dna.toplevel.fa.fai
│   ├── extended_annotations.fa
│   ├── extended_annotations.gtf
│   ├── FL_counts.csv
│   ├── kallisto_bambu
│   ├── SJ_Files
│   │   ├── SRR7072111SJ.out.tab
│   │   ├── SRR7072112SJ.out.tab
│   │   ├── SRR7072113SJ.out.tab
│   │   └── SRR7072114SJ.out.tab
│   ├── SRR707211
│   │   ├── abundance.h5
│   │   ├── abundance.tsv
│   │   └── run_info.json
│   ├── SRR707212
│   │   ├── abundance.h5
│   │   ├── abundance.tsv
│   │   └── run_info.json
│   ├── SRR707213
│   │   ├── abundance.h5
│   │   ├── abundance.tsv
│   │   └── run_info.json
│   └── SRR707214
│       ├── abundance.h5
│       ├── abundance.tsv
│       └── run_info.json
└── short_reads
    ├── SRR7072111.fastq
    ├── SRR7072112.fastq
    ├── SRR7072113.fastq
    └── SRR7072114.fastq

11 directories, 37 files
(sqanti3) X:~/Documents/Projects/With/X/04_28_2025_ONT$ python3 /home/X/Documents/Tools/sqanti3/release_sqanti3/sqanti3_qc.py --isoforms input_data/extended_annotations.gtf --refGTF input_data/Drosophila_melanogaster.BDGP6.46.112.gtf --refFasta input_data/Drosophila_melanogaster.BDGP6.46.dna.toplevel.fa -o D8_SQANTI -d D8_SQANTI_BAMBU --SR_bam input_data/Alignments/ -c input_data/SJ_Files/ -t 12 --force_id_ignore --expression input_data/abundances/

    =====================
      ░██████╗░░█████╗░
      ██╔═══██╗██╔══██╗
      ██║██╗██║██║░░╚═╝
      ╚██████╔╝██║░░██╗
      ░╚═██╔═╝░╚█████╔╝
      ░░░╚═╝░░░░╚════╝░
    =====================
    
[ERROR:2025-04-28 15:59:58,820] File input_data/abundances/ not found. Abort!
(sqanti3) X:~/Documents/Projects/With/X/04_28_2025_ONT$ python3 /home/X/Documents/Tools/sqanti3/release_sqanti3/sqanti3_qc.py --isoforms input_data/extended_annotations.gtf --refGTF input_data/Drosophila_melanogaster.BDGP6.46.112.gtf --refFasta input_data/Drosophila_melanogaster.BDGP6.46.dna.toplevel.fa -o D8_SQANTI -d D8_SQANTI_BAMBU --SR_bam input_data/Alignments/ -c input_data/SJ_Files/ -t 12 --force_id_ignore --expression input_data/abundances/SRR707211_abundance.tsv,input_data/abundances/SRR707212_abundance.tsv,input_data/abundances/SRR707213_abundance.tsv,input_data/abundances/SRR707214_abundance.tsv

    =====================
      ░██████╗░░█████╗░
      ██╔═══██╗██╔══██╗
      ██║██╗██║██║░░╚═╝
      ╚██████╔╝██║░░██╗
      ░╚═██╔═╝░╚█████╔╝
      ░░░╚═╝░░░░╚════╝░
    =====================
    
[ERROR:2025-04-28 16:00:06,244] File input_data/abundances/SRR707211_abundance.tsv,input_data/abundances/SRR707212_abundance.tsv,input_data/abundances/SRR707213_abundance.tsv,input_data/abundances/SRR707214_abundance.tsv not found. Abort!
```

**Comment by pabloati** [comment]
Hi Mujeeb, 

Sorry for the issue, The old buggy check for the expression files was left in the code during the merge of the new release into the main SQANTI3. Now (for sure ;) ) should be fixed. I updated the release file, so you can download it again :)
